name: Render Signature Images

on:
  push:
    branches: [ main ]
    paths:
      - 'aividz.online/logo.svg'
      - 'fontofmadness.uk/logo.svg'
      - 'madgodnerevar.uk/logo.svg'
      - 'nebula-project.org/logo.svg'
      - 'speldridge/logo.svg'
      - '.github/workflows/render-signatures.yml'
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Inkscape
        run: |
          sudo apt-get update
          sudo apt-get install -y inkscape

      - name: Render all folders (SVG → PNG 320/640)
        shell: bash
        run: |
          set -euo pipefail
          folders=(aividz.online fontofmadness.uk madgodnerevar.uk nebula-project.org speldridge)
          for f in "${folders[@]}"; do
            echo "Rendering $f"
            inkscape "$f/logo.svg" --export-type=png --export-filename="$f/logo.png" -w 320
            inkscape "$f/logo.svg" --export-type=png --export-filename="$f/logo@2x.png" -w 640
            ls -l "$f"/logo*.png
          done

      - name: Commit rendered images
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(images): render PNGs from SVG (all folders)"
          file_pattern: |
            aividz.online/logo*.png
            fontofmadness.uk/logo*.png
            madgodnerevar.uk/logo*.png
            nebula-project.org/logo*.png
            speldridge/logo*.png
