name: Render Signature Images

on:
  push:
    branches: [ main ]
    paths:
      - 'brands.yaml'
      - 'aividz.online/logo.svg'
      - 'fontofmadness.uk/logo.svg'
      - 'madgodnerevar.uk/logo.svg'
      - 'nebula-project.org/logo.svg'
      - 'speldridge/logo.svg'
      - '.github/workflows/render-signatures.yml'
      - 'scripts/gen_logos.py'
  workflow_dispatch:

jobs:
  generate-svgs:
    # Needed so the job can push regenerated SVGs
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python deps
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          python3 -m pip install pyyaml
      - name: Generate SVGs from brands.yaml
        run: |
          chmod +x scripts/gen_logos.py
          python3 scripts/gen_logos.py
      - name: Commit updated SVGs (if any)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(branding): regenerate SVGs from brands.yaml"
          file_pattern: |
            aividz.online/logo.svg
            fontofmadness.uk/logo.svg
            madgodnerevar.uk/logo.svg
            nebula-project.org/logo.svg
            speldridge/logo.svg

  render-pngs:
    needs: generate-svgs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy: { max-parallel: 1 }
    steps:
      - uses: actions/checkout@v4
      - name: Install Inkscape
        run: |
          sudo apt-get update
          sudo apt-get install -y inkscape
      - name: Pull latest main
        run: git pull --rebase origin main
      - name: Render PNG 320/640 (drawing bounds)
        run: |
          set -euo pipefail
          for folder in */logo.svg; do
            dir="$(dirname "$folder")"
            (
              cd "$dir"
              GTK_USE_PORTAL=0 inkscape --without-gui logo.svg --export-type=png --export-filename=logo.png   -w 320 --export-area-drawing
              GTK_USE_PORTAL=0 inkscape --without-gui logo.svg --export-type=png --export-filename=logo@2x.png -w 640 --export-area-drawing
              ls -l
            )
          done
      - name: Commit rendered images
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(images): render PNGs from SVG"
          file_pattern: |
            */logo*.{svg,png}
            */signature/*.html
          push_options: '--force-with-lease'
