name: Render Signature Images

on:
  push:
    branches: [ main ]
    paths:
      - 'aividz.online/logo.svg'
      - 'fontofmadness.uk/logo.svg'
      - 'madgodnerevar.uk/logo.svg'
      - 'nebula-project.org/logo.svg'
      - 'speldridge/logo.svg'
      - '.github/workflows/render-signatures.yml'
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        folder:
          - aividz.online
          - fontofmadness.uk
          - madgodnerevar.uk
          - nebula-project.org
          - speldridge

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Inkscape
        run: |
          sudo apt-get update
          sudo apt-get install -y inkscape

      - name: Render ${{ matrix.folder }} (SVG → PNG 1x/2x)
        working-directory: ./${{ matrix.folder }}
        run: |
          set -euo pipefail
          inkscape logo.svg --export-type=png --export-filename=logo.png -w 160
          inkscape logo.svg --export-type=png --export-filename=logo@2x.png -w 320
          ls -l

      - name: Commit rendered images
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(images): render PNGs from SVG"
          file_pattern: |
            aividz.online/logo*.png
            fontofmadness.uk/logo*.png
            madgodnerevar.uk/logo*.png
            nebula-project.org/logo*.png
            speldridge/logo*.png
